# Prettier (formatter) configuration
---
# semi set to true means that Prettier will add semicolons when necessary.
semi: true
# trailingComma set to none means that Prettier will remove
# any trailing commas at the end of objects.
trailingComma: none
# printWidth set to 200 specifies that the printer
# will wrap any lines that exceed 80 characters.
printWidth: 160
bracketSameLine: true
bracketSpacing: true
tabWidth: 2
useTabs: false
arrowParens: avoid
htmlWhitespaceSensitivity: "ignore"
plugins:
  - "@shopify/prettier-plugin-liquid"
overrides:
  - files: "*.html"
    options:
      semi: true
      bracketSameLine: true
  - files: "*.js"
    options:
      singleQuote: true
  - files: "*.svg"
    options:
      parser: html
  - files:
      - "_layouts/*.html"
      - "_includes/*.html"
      - "_posts/*.html"
      - "_pages/*.html"
    options:
      bracketSameLine: true
      parser: "liquid-html"
      singleAttributePerLine: false
      singleQuote: false
  - files:
      - "*.md"
    options:
      parser: markdown
      proseWrap: always
