# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

locale: "de-DE"
title: Innovationsverbund Öffentliche Gesundheit e.V.
email: kontakt@inoeg.de
description: >- # this means to ignore newlines until "baseurl:"
  Wir verbinden den ÖGD mit Innovationen.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.inoeg.de" # the base hostname & protocol for your site, e.g. http://example.com

# Specify used plugins here and in the Gemfile to ensure full flexibility.
# Note that github pages only supports plugins that are specified in _config.yml
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap

# List the same plugins again to  mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .vscode/
  - .github/
  - .jekyll-cache/
  - .ruby-lsp/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - bin/

# But make sure to process the following directories and their entries.
include:
  - _pages # static content
  - _posts # for blog / news posts

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url:
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:
